USE customer_behaviour;

SELECT * FROM customer;

#1 What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

#2 Which customers used a discount but still spent more than average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied='Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);

#3 Which are the top5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS average_review
FROM customer
GROUP BY item_purchased
ORDER BY 2 DESC
LIMIT 5;

#4 Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS average
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

#5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?
SELECT subscription_status, AVG(purchase_amount) AS average_spent, COUNT(*) AS count, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY subscription_status
ORDER BY revenue, average_spent DESC;

#6 Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, ROUND(SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)*100/COUNT(*),2) AS percentOfPurchases
FROM customer
GROUP BY item_purchased
ORDER BY 2 DESC;

#7 Segment customers into New, Returning and Loyal based on their total number of previous purchases and show the count of each segment
SELECT (CASE WHEN previous_purchases=1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal' END)  AS customer_status, COUNT(*) AS count
FROM customer
GROUP BY 1;

#8 What are the top 3 most purchased products with in each category?
WITH temp AS (SELECT category, item_purchased, COUNT(customer_id) AS total_orders, row_number() over(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS series
FROM customer
GROUP BY category, item_purchased)

SELECT series, category, item_purchased, total_orders
FROM temp
WHERE series <=3;

#9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(previous_purchases) AS repeat_buyers
FROM customer 
WHERE previous_purchases>5
GROUP BY subscription_status;

#10 What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY age_group
ORDER BY 2 DESC;





















